### ISSUE TITLE
Attributes generator crashes with integer as input

### ISSUE THREAD

**Issue by cardinot** [evoplex/evoplex#19]
**System info:**
- Evoplex Version: 0.2.1
- OS: all

**Bug description:**
Evoplex crashes when passing an integer into the attrs generator (nodes or edges).

**Steps to reproduce:**
Steps to reproduce the behavior (if applicable, add screenshots to help explain your problem):
1. Create a new project
2. Create a new experiment with 1 node (integer)
3. Evoplex crashes

**Hint for people interested in fixing it:**
Look at [AttrsGenerator::parse](https://github.com/evoplex/evoplex/blob/master/src/core/attrsgenerator.cpp)

**Comment by Sedictious** [comment]
@cardinot I accidentally stumbled upon this myself. Actually, there is also a UI issue where the "node generator box" (the one with the 3 dots) isn't displayed if the side-bar is narrow enough, leading to more head-scratching moments.

Anyway, I'd like to tackle the problem and I was wondering what the best approach would be:

* Silently pass a default function and mode (probably a _really_ bad idea, as this creates more problem than it resolves)

* Break up the different attributes (number of nodes, function, mode)

* Simply return the error warning (_the following attributes are invalid or missing..._)

I'm leaning towards the latter, but I'd like to get a second in case a better approach exists!

**Comment by cardinot** [comment]
Hi @Sedictious. Thanks for working on this issue.

> Actually, there is also a UI issue where the "node generator box" (the one with the 3 dots) isn't displayed if the side-bar is narrow enough, leading to more head-scratching moments.

It seems to be a Qt-related issue. I can reproduce the bug in Qt5.12, but it works fine in Qt5.9.5. In any case, it might be possible to make it work fine in both versions. Anyway, we should move this discussion to another issue, so could you please open a [new issue](https://github.com/evoplex/evoplex/issues/new/choose) for this specific bug?

> Anyway, I'd like to tackle the problem and I was wondering what the best approach would be

Please, have a look at the documentation of the [parse](https://github.com/evoplex/evoplex/blob/cbfac5af0ad76b7c88a7ea296d94785692da3048/src/core/include/attrsgenerator.h#L70) function. An integer is an alias for `*integer;min`. Hint: check [this line](https://github.com/evoplex/evoplex/blob/809b37ff7442ca4c7545771c7e0ab09c93b775ae/src/core/attrsgenerator.cpp#L42).
