### ISSUE TITLE
Experiment Designer: vertical scrollbar is hiding the buttons and fields

### ISSUE THREAD

**Issue by Sedictious** [evoplex/evoplex#27]
**System info:**
 - Evoplex Version: 0.2.1
 - Operating System: Windows10 64bit

**Bug description:**
Some UI elements disappear when the Experiment Designer is minimized

**Additional info:**
- Qt Version: 5.12.2

**Steps to reproduce:**

1. Open the experiment designer
2. Minimize its width

**Expected behavior**
Some buttons are missing and/or misplaced as indicated bellow:

![](https://i.imgur.com/TMu9nMm.png)

**Comment by cardinot** [comment]
I can confirm the issue on Fedora29, Qt5.12.2. However, it works fine for Qt5.9.5.

**Comment by cardinot** [comment]
@Sedictious, please let me know if it fixes the issue in your end (Windows).
Thanks ;)

**Comment by Sedictious** [comment]
@cardinot Can confirm, it works!
